server:
  port: 8070
spring:
  datasource:
    url: jdbc:sqlserver://savingsdbserver.database.windows.net:1433;database=savingsdb;user=fiona@savingsdbserver;password=password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: fiona
    password: password@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


  application:
    name: savingsManagementAPi


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

